//auth and userprofile
export const MYPROFILE_LOADED = "MYPROFILE_LOADED";
export const MYPROFILE_LOADING = "MYPROFILE_LOADING";
export const MYPROFILE_UPDATING = "MYPROFILE_UPDATING";
export const MYPROFILE_UPDATED = "MYPROFILE_UPDATED";
export const MYPROFILE_UPDATE_ERROR = "MYPROFILE_UPDATE_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_VALIDATING = "LOGIN_VALIDATING";

//user
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USERDETAILS_LOADED = "USERDETAILS_LOADED";
export const USERDETAILS_LOADING = "USERDETAILS_LOADING";
export const USERDETAILS_ERROR = "USERDETAILS_ERROR";
export const USERLIST_LOADED = "USERLIST_LOADED";
export const USERLIST_ERROR = "USERLIST_ERROR";
export const USERLIST_LOADING = "USERLIST_LOADING";
export const USER_UPDATING = "USER_UPDATING";
export const USER_UPDATED = "USER_UPDATED";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";
export const RESET_USER_STATE = "RESET_USER_STATE";
export const USERS_DELETED = "USERS_DELETED";
export const USERS_DELETE_ERROR = "USERS_DELETE_ERROR";
export const USERS_DELETING = "USERS_DELETING";
export const USER_UPDATED_LIST = "USER_UPDATED_LIST";
export const USER_DELETED_LIST = "USER_DELETED_LIST";
export const USER_PREFERENCE_UPDATED = "USER_PREFERENCE_UPDATED";
export const USER_PREFERENCE_UPDATING = "USER_PREFERENCE_UPDATING";
export const USER_PREFERENCE_UPDATE_ERROR = "USER_PREFERENCE_UPDATE_ERROR";
export const USER_PREFERENCE_LOADED = "USER_PREFERENCE_LOADED";
export const USER_PREFERENCE_LOADING = "USER_PREFERENCE_LOADING";
export const USER_PREFERENCE_LOAD_ERROR = "USER_PREFERENCE_LOAD_ERROR";

//appointment
export const USER_TIMESLOT_LOADED = "USER_TIMESLOT_LOADED";
export const USER_TIMESLOT_LOADING = "USER_TIMESLOT_LOADING";
export const USER_TIMESLOT_LOAD_ERROR = "USER_TIMESLOT_LOAD_ERROR";
export const DATE_FORMAT = "YYYY-MM-DD";
export const YEAR_MONTH_FORMAT = "YYYY-MM";
export const TIME_FORMAT = "HH:mm";
export const DATE_TIME_FORMAT = "YYYY-MM-DD[T]HH:mm";
export const DATE_TIME_FORMAT_AM_PM = "YYYY-MM-DD[T]hh:mm A";
export const DATE_FORMAT_WORDINGS = "MMM DD YYYY";
export const DATE_TIME_WORDINGS = "MMM DD YYYY [at] h:mm A";
export const TIME_FORMAT_AM_PM = "h:mm A";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_SELECTED_TIME = "SET_SELECTED_TIME";
export const SET_TIMEZONE = "SET_TIMEZONE";
export const SET_USER = "SET_USER";
export const SET_SLOT_DURATION = "SET_SLOT_DURATION";
export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
export const BOOK_APPOINTMENT_ERROR = "BOOK_APPOINTMENT_ERROR";
export const BOOK_APPOINTMENT_SUCCESS = "BOOK_APPOINTMENT_SUCCESS";
export const RESET_BOOKING_STATE = "RESET_BOOKING_STATE";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const UPDATE_APPOINTMENT_ERROR = "UPDATE_APPOINTMENT_ERROR";
export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS";
export const RESET_UPDATE_APPOINTMENT_STATE = "RESET_UPDATE_APPOINTMENT_STATE";
export const APPOINTMENTS_LOADING = "APPOINTMENTS_LOADING";
export const APPOINTMENTS_LOADED = "APPOINTMENTS_LOADED";
export const APPOINTMENTS_FETCH_ERROR = "APPOINTMENTS_FETCH_ERROR";
export const APPOINTMENT_DETAILS_LOADING = "APPOINTMENT_DETAILS_LOADING";
export const APPOINTMENT_DETAILS_LOADED = "APPOINTMENT_DETAILS_LOADED";
export const APPOINTMENT_DETAILS_FETCH_ERROR = "APPOINTMENT_DETAILS_FETCH_ERROR";

//common
export const ROLES_ERROR = "ROLES_ERROR";
export const ROLES_LOADING = "ROLES_LOADING";
export const ROLES_LOADED = "ROLES_LOADED";
export const TIME_ZONE_LOADING = "TIME_ZONE_LOADING";
export const TIME_ZONE_LOADED = "TIME_ZONE_LOADED";
export const DATA_PER_PAGE = 10;


//responsive
export const isMobile = window.innerWidth <= 600 ? true : false;
export const responsiveDrawerWidth = window.innerWidth <= 600 ? "100%" : 700;