# Generated by Django 2.2.1 on 2019-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Appointment'), ('Closed', 'Closed Appointment'), ('Not Interested', 'Not Interested')], default='pending', max_length=20),
        ),
    ]
