# Generated by Django 2.2.1 on 2019-07-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20190730_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
