# Generated by Django 2.2.1 on 2019-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20190730_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Appointment'), ('Closed', 'Closed Appointment'), ('Not Interested', 'Not Interested')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_contact_mobile_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_email_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
