# Generated by Django 2.2.1 on 2019-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20190802_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['start_time'], 'permissions': [('can_view_own_appointments', 'Can view own appointments'), ('can_view_peers_appointments', 'Can view peers appointments')]},
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_contact_mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
