# Generated by Django 2.2.1 on 2019-10-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20190805_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='event_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='lead_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed'), ('Not Interested', 'Not Interested')], default='Pending', max_length=50),
        ),
    ]
