# Generated by Django 2.2.1 on 2019-10-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20191008_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_email_id',
            field=models.CharField(max_length=50),
        ),
    ]
