# Generated by Django 2.2.1 on 2019-07-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizations',
            options={'verbose_name_plural': 'Organizations'},
        ),
    ]
