# Generated by Django 2.2.1 on 2019-07-22 08:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190719_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='available_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=25),
        ),
    ]
