# Generated by Django 2.2.1 on 2019-08-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190724_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_own_appointments', 'Can view own appointments'), ('can_view_peers_appointments', 'Can view peers appointments')]},
        ),
    ]
